name: Keep Streamlit App Alive

on:
  schedule:
    # Run every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Streamlit App
      run: |
        echo "🚀 Pinging Streamlit app at $(date)"
        
        # Simple ping - don't fail if app is sleeping
        curl -L -s -m 30 --retry 3 --retry-delay 10 \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" \
          https://wsf-chat.streamlit.app/ || echo "Ping attempt completed (app may have been sleeping)"
        
        echo "✅ Keep-alive sequence finished at $(date)"
