yamlCopyname: Keep Streamlit App Alive

on:
  schedule:
    # Run every 4 hours (more reasonable than 30 minutes)
    - cron: '0 */4 * * *'
  # Allows manual trigger from GitHub web interface
  workflow_dispatch:

jobs:
  ping_streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: |
          echo "Pinging Streamlit app at $(date)"
          curl -IsS "https://wsf-chat.streamlit.app/" -o /dev/null
          echo "Ping completed successfully"
